version: 1.0.{build}
image: Visual Studio 2017

environment:

  matrix:

  - PYTHON: "C:\\Python27-x64"
  - PYTHON: "C:\\Python36-x64"
  - PYTHON: "C:\\Python37-x64"


build: off

install:
# To run Nodejs workflow integ tests
- ps: Install-Product node 8.10
- ps: $env:Path = "$env:PYTHON;$env:PYTHON\\Scripts;$env:PYTHON\\bin;$env:Path"
- ps: python --version
- ps: python -m pip install -r requirements/dev.txt
- ps: python -m pip install -e .
- ps: python --version
- ps: $env:Path = "C:\\Ruby25-x64\\bin;$env:Path"
- ps: ruby --version
- ps: gem install bundler --no-ri --no-rdoc
- ps: bundler --version

test_script:
- ps: python -m pytest --cov aws_lambda_builders --cov-report term-missing tests/unit tests/functional
- ps: python -m pytest tests/integration
